project_id = "kdbgwmtihgmialrmaecn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
api_url = "https://kdbgwmtihgmialrmaecn.supabase.co"
port = 54324

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[functions]
verify_jwt = true

[functions.seed-data]
verify_jwt = true

[functions.send-signup-invitation]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.get-revenuecat-config]
verify_jwt = true

[functions.search-nearby-places]
verify_jwt = true

[functions.test-google-places]
verify_jwt = true

# Public endpoints necessary before user has a session
[functions.verify-signup-token]
verify_jwt = false

[functions.verify-email-and-signup]
verify_jwt = false

# Push notifications sender (requires user auth to respect RLS)
[functions.send-push]
verify_jwt = true

# Scheduled engagement notifier (invoked by scheduler or manually)
[functions.engagement-notifier]
verify_jwt = false

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://kdbgwmtihgmialrmaecn.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
enable_signup = true
enable_email_confirmations = false

[edge-runtime]
policy = "per_worker"
inspector_port = 8083