-- Remove existing cards and create 200 new ones without voice responses
DELETE FROM deck_cards;

-- Insert 200 cards across 3 response types (action, text, photo)
-- Action cards (80 cards) - Physical tasks requiring in-person interaction
INSERT INTO deck_cards (prompt, category, subcategory, timer_seconds, timer_category, difficulty_level, intimacy_level, response_type, requires_action) VALUES
-- Romantic & Sweet Action Cards (25 cards)
('Give me a gentle 3-minute shoulder massage while I tell you about my day', 'Romantic & Sweet', 'Physical Touch', 180, 'medium', 1, 2, 'action', true),
('Slow dance with me to our favorite song right now', 'Romantic & Sweet', 'Connection', 240, 'medium', 1, 2, 'action', true),
('Feed me three bites of something delicious while maintaining eye contact', 'Romantic & Sweet', 'Intimacy', 120, 'short', 1, 2, 'action', true),
('Give me soft kisses on my forehead, cheeks, and nose', 'Romantic & Sweet', 'Affection', 90, 'short', 1, 3, 'action', true),
('Brush or play with my hair for 5 minutes', 'Romantic & Sweet', 'Physical Touch', 300, 'long', 1, 2, 'action', true),
('Trace "I love you" on my back with your finger', 'Romantic & Sweet', 'Communication', 60, 'short', 1, 2, 'action', true),
('Give me a surprise hug from behind and hold me for 30 seconds', 'Romantic & Sweet', 'Affection', 30, 'short', 1, 2, 'action', true),
('Kiss my hand like a romantic gentleman/lady', 'Romantic & Sweet', 'Romance', 30, 'short', 1, 2, 'action', true),
('Create a cozy fort with pillows and blankets together', 'Romantic & Sweet', 'Playfulness', 600, 'long', 1, 1, 'action', true),
('Give me a foot massage while we watch something together', 'Romantic & Sweet', 'Physical Touch', 300, 'long', 1, 2, 'action', true),
('Carry me bridal style for 10 steps', 'Romantic & Sweet', 'Playfulness', 30, 'short', 2, 2, 'action', true),
('Surprise me with butterfly kisses on my neck', 'Romantic & Sweet', 'Affection', 60, 'short', 1, 3, 'action', true),
('Hold both my hands and look into my eyes for 1 minute without talking', 'Romantic & Sweet', 'Connection', 60, 'short', 1, 2, 'action', true),
('Give me a warm, lingering hug that lasts at least 20 seconds', 'Romantic & Sweet', 'Affection', 20, 'short', 1, 2, 'action', true),
('Massage my temples gently while I close my eyes', 'Romantic & Sweet', 'Physical Touch', 120, 'short', 1, 1, 'action', true),
('Spin me around like we''re in a movie scene', 'Romantic & Sweet', 'Playfulness', 30, 'short', 1, 2, 'action', true),
('Kiss every fingertip on both my hands', 'Romantic & Sweet', 'Affection', 90, 'short', 1, 3, 'action', true),
('Give me a piggyback ride around the room', 'Romantic & Sweet', 'Playfulness', 60, 'short', 2, 1, 'action', true),
('Cuddle with me in the coziest position for 5 minutes', 'Romantic & Sweet', 'Physical Touch', 300, 'long', 1, 2, 'action', true),
('Draw a heart on my palm with your finger and kiss it', 'Romantic & Sweet', 'Romance', 60, 'short', 1, 2, 'action', true),
('Give me a surprise kiss on the spot that makes me smile', 'Romantic & Sweet', 'Affection', 30, 'short', 1, 3, 'action', true),
('Wrap me in a blanket and hold me like a burrito', 'Romantic & Sweet', 'Playfulness', 120, 'short', 1, 2, 'action', true),
('Give me gentle neck kisses while standing behind me', 'Romantic & Sweet', 'Affection', 90, 'short', 1, 3, 'action', true),
('Rock me back and forth while we''re sitting together', 'Romantic & Sweet', 'Physical Touch', 180, 'medium', 1, 2, 'action', true),
('Pick me up and twirl me around 3 times', 'Romantic & Sweet', 'Playfulness', 45, 'short', 2, 2, 'action', true),

-- Flirty & Playful Action Cards (20 cards)
('Give me your most seductive smile and wink', 'Flirty & Playful', 'Attraction', 15, 'short', 1, 2, 'action', true),
('Whisper something flirty in my ear that makes me blush', 'Flirty & Playful', 'Communication', 30, 'short', 1, 3, 'action', true),
('Do your sexiest dance move for me right now', 'Flirty & Playful', 'Performance', 60, 'short', 2, 2, 'action', true),
('Give me a playful bite somewhere unexpected', 'Flirty & Playful', 'Teasing', 15, 'short', 1, 3, 'action', true),
('Lick something sweet off my lips', 'Flirty & Playful', 'Intimacy', 30, 'short', 2, 4, 'action', true),
('Pin me against the wall for 10 seconds with intense eye contact', 'Flirty & Playful', 'Dominance', 10, 'short', 2, 4, 'action', true),
('Give me a lap dance to our favorite song', 'Flirty & Playful', 'Seduction', 240, 'medium', 3, 4, 'action', true),
('Bite my lower lip gently during our next kiss', 'Flirty & Playful', 'Kissing', 30, 'short', 2, 4, 'action', true),
('Spank me playfully and tell me I''ve been naughty', 'Flirty & Playful', 'Teasing', 15, 'short', 2, 4, 'action', true),
('Give me a hickey in a place only you will see', 'Flirty & Playful', 'Marking', 60, 'short', 2, 4, 'action', true),
('Undress me with your eyes and tell me what you''re thinking', 'Flirty & Playful', 'Mental Seduction', 60, 'short', 2, 3, 'action', true),
('Pull me close by my belt loops or waistband', 'Flirty & Playful', 'Attraction', 15, 'short', 2, 3, 'action', true),
('Give me bedroom eyes from across the room', 'Flirty & Playful', 'Seduction', 30, 'short', 1, 2, 'action', true),
('Whisper your favorite thing about my body in my ear', 'Flirty & Playful', 'Communication', 30, 'short', 1, 3, 'action', true),
('Trace my curves with just your fingertips', 'Flirty & Playful', 'Touch', 120, 'short', 2, 4, 'action', true),
('Give me a passionate kiss that lasts at least 30 seconds', 'Flirty & Playful', 'Kissing', 30, 'short', 1, 3, 'action', true),
('Do a striptease to remove just one piece of clothing', 'Flirty & Playful', 'Seduction', 120, 'short', 3, 4, 'action', true),
('Grab my face and kiss me like you mean it', 'Flirty & Playful', 'Passion', 30, 'short', 2, 3, 'action', true),
('Give me a massage that gets increasingly sensual', 'Flirty & Playful', 'Touch', 300, 'long', 2, 4, 'action', true),
('Show me how you want to be touched by demonstrating on yourself', 'Flirty & Playful', 'Education', 120, 'short', 3, 4, 'action', true),

-- Intimate & Vulnerable Action Cards (20 cards)
('Hold me skin-to-skin for 5 minutes in comfortable silence', 'Intimate & Vulnerable', 'Connection', 300, 'long', 2, 4, 'action', true),
('Give me a full body massage with oils or lotion', 'Intimate & Vulnerable', 'Intimacy', 900, 'long', 2, 3, 'action', true),
('Undress me slowly while maintaining eye contact', 'Intimate & Vulnerable', 'Intimacy', 180, 'medium', 3, 5, 'action', true),
('Kiss every part of my body I''m insecure about', 'Intimate & Vulnerable', 'Acceptance', 300, 'long', 2, 4, 'action', true),
('Share a shower or bath together for 10 minutes', 'Intimate & Vulnerable', 'Intimacy', 600, 'long', 3, 5, 'action', true),
('Give me oral pleasure for as long as I want', 'Intimate & Vulnerable', 'Sexual Intimacy', 600, 'long', 4, 5, 'action', true),
('Let me explore your body however I want for 10 minutes', 'Intimate & Vulnerable', 'Exploration', 600, 'long', 3, 5, 'action', true),
('Make love to me in our favorite position', 'Intimate & Vulnerable', 'Sexual Intimacy', 1200, 'long', 4, 5, 'action', true),
('Hold me while I cry or be vulnerable without trying to fix it', 'Intimate & Vulnerable', 'Emotional Support', 300, 'long', 1, 3, 'action', true),
('Sleep naked together tonight', 'Intimate & Vulnerable', 'Intimacy', 28800, 'long', 2, 4, 'action', true),
('Kiss me during our most intimate moment', 'Intimate & Vulnerable', 'Connection', 30, 'short', 3, 5, 'action', true),
('Touch me in the way that drives me wildest', 'Intimate & Vulnerable', 'Sexual Intimacy', 300, 'long', 3, 5, 'action', true),
('Let me take complete control in bed tonight', 'Intimate & Vulnerable', 'Power Exchange', 1800, 'long', 4, 5, 'action', true),
('Worship my body like it''s sacred', 'Intimate & Vulnerable', 'Reverence', 600, 'long', 3, 5, 'action', true),
('Make me feel completely desired with your touch', 'Intimate & Vulnerable', 'Desire', 600, 'long', 3, 4, 'action', true),
('Hold me after we make love until I fall asleep', 'Intimate & Vulnerable', 'Aftercare', 1800, 'long', 2, 4, 'action', true),
('Blindfold me and touch me in surprising ways', 'Intimate & Vulnerable', 'Sensory Play', 600, 'long', 4, 5, 'action', true),
('Wake me up with gentle kisses tomorrow morning', 'Intimate & Vulnerable', 'Tenderness', 300, 'long', 1, 3, 'action', true),
('Carry me to bed and tuck me in', 'Intimate & Vulnerable', 'Care', 120, 'short', 1, 2, 'action', true),
('Breathe with me in sync for 2 minutes while touching', 'Intimate & Vulnerable', 'Connection', 120, 'short', 2, 3, 'action', true),

-- Daily Life & Habits Action Cards (15 cards)
('Make me my favorite drink exactly how I like it', 'Daily Life & Habits', 'Care', 300, 'long', 1, 1, 'action', true),
('Give me a wake-up kiss before I get out of bed', 'Daily Life & Habits', 'Morning Ritual', 30, 'short', 1, 2, 'action', true),
('Brush my teeth with me while being silly', 'Daily Life & Habits', 'Routine', 120, 'short', 1, 1, 'action', true),
('Cook something together without a recipe', 'Daily Life & Habits', 'Cooperation', 1800, 'long', 2, 1, 'action', true),
('Do my least favorite chore for me today', 'Daily Life & Habits', 'Service', 1800, 'long', 1, 1, 'action', true),
('Pack my lunch with a sweet note for tomorrow', 'Daily Life & Habits', 'Care', 600, 'long', 1, 1, 'action', true),
('Give me a goodnight kiss and tuck me in', 'Daily Life & Habits', 'Evening Ritual', 60, 'short', 1, 2, 'action', true),
('Help me get dressed and zip up my outfit', 'Daily Life & Habits', 'Assistance', 120, 'short', 1, 2, 'action', true),
('Surprise me by cleaning something I''ve been meaning to clean', 'Daily Life & Habits', 'Service', 1800, 'long', 1, 1, 'action', true),
('Feed our pets together and talk about our day', 'Daily Life & Habits', 'Teamwork', 300, 'long', 1, 1, 'action', true),
('Take out the trash and do one extra chore without being asked', 'Daily Life & Habits', 'Initiative', 900, 'long', 1, 1, 'action', true),
('Make the bed together tomorrow morning', 'Daily Life & Habits', 'Partnership', 300, 'long', 1, 1, 'action', true),
('Bring me a snack without me asking', 'Daily Life & Habits', 'Thoughtfulness', 180, 'medium', 1, 1, 'action', true),
('Help me with my skincare routine tonight', 'Daily Life & Habits', 'Care', 600, 'long', 1, 2, 'action', true),
('Set up my phone charger exactly where I like it', 'Daily Life & Habits', 'Consideration', 60, 'short', 1, 1, 'action', true);

-- Text response cards (80 cards) - Questions requiring written answers
INSERT INTO deck_cards (prompt, category, subcategory, timer_seconds, timer_category, difficulty_level, intimacy_level, response_type, requires_action) VALUES
-- Romantic & Sweet Text Cards (20 cards)
('Describe the exact moment you realized you were falling for me', 'Romantic & Sweet', 'Love Story', 300, 'long', 2, 3, 'text', false),
('Write me a short love poem using our inside jokes', 'Romantic & Sweet', 'Creativity', 300, 'long', 2, 2, 'text', false),
('What are three things about our relationship that make you happiest?', 'Romantic & Sweet', 'Gratitude', 180, 'medium', 1, 2, 'text', false),
('Describe your ideal romantic evening with me in detail', 'Romantic & Sweet', 'Romance', 240, 'medium', 1, 2, 'text', false),
('What song reminds you of me and why?', 'Romantic & Sweet', 'Music', 180, 'medium', 1, 2, 'text', false),
('Write about a time I made you feel incredibly loved', 'Romantic & Sweet', 'Memories', 240, 'medium', 2, 3, 'text', false),
('What is your favorite physical feature about me and why?', 'Romantic & Sweet', 'Attraction', 120, 'short', 1, 2, 'text', false),
('Describe what love means to you using only 5 words, then explain', 'Romantic & Sweet', 'Philosophy', 180, 'medium', 2, 3, 'text', false),
('What is the most romantic gesture I could surprise you with?', 'Romantic & Sweet', 'Desires', 180, 'medium', 1, 2, 'text', false),
('Write me a love letter like we''re long-distance lovers', 'Romantic & Sweet', 'Communication', 300, 'long', 2, 3, 'text', false),
('What makes me different from anyone you''ve ever loved?', 'Romantic & Sweet', 'Uniqueness', 240, 'medium', 2, 3, 'text', false),
('Describe the moment you knew you wanted to commit to me', 'Romantic & Sweet', 'Commitment', 240, 'medium', 3, 4, 'text', false),
('What about our relationship surprised you the most?', 'Romantic & Sweet', 'Discovery', 180, 'medium', 2, 3, 'text', false),
('Write about why you choose me every day', 'Romantic & Sweet', 'Choice', 240, 'medium', 3, 4, 'text', false),
('What is your favorite way that I show you love?', 'Romantic & Sweet', 'Love Languages', 180, 'medium', 1, 2, 'text', false),
('Describe a dream you had about us', 'Romantic & Sweet', 'Dreams', 180, 'medium', 1, 2, 'text', false),
('What would you tell someone who asked why you love me?', 'Romantic & Sweet', 'Explanation', 240, 'medium', 2, 3, 'text', false),
('Write about the first time you saw me and what you thought', 'Romantic & Sweet', 'First Impressions', 240, 'medium', 1, 2, 'text', false),
('What is one romantic tradition you want us to start?', 'Romantic & Sweet', 'Traditions', 180, 'medium', 1, 2, 'text', false),
('Describe how I make ordinary moments feel special', 'Romantic & Sweet', 'Everyday Magic', 240, 'medium', 2, 3, 'text', false),

-- Future & Dreams Text Cards (20 cards)
('Describe our life together in 10 years', 'Future & Dreams', 'Vision', 300, 'long', 2, 3, 'text', false),
('What are three goals you want us to achieve together this year?', 'Future & Dreams', 'Goals', 240, 'medium', 2, 2, 'text', false),
('Where do you see us traveling together next?', 'Future & Dreams', 'Travel', 180, 'medium', 1, 2, 'text', false),
('What kind of home do you want us to create together?', 'Future & Dreams', 'Home', 240, 'medium', 2, 3, 'text', false),
('Describe the legacy you want our love story to leave', 'Future & Dreams', 'Legacy', 300, 'long', 3, 4, 'text', false),
('What tradition do you want to pass down to our future family?', 'Future & Dreams', 'Traditions', 240, 'medium', 2, 3, 'text', false),
('How do you want us to celebrate our 50th anniversary?', 'Future & Dreams', 'Celebration', 240, 'medium', 2, 3, 'text', false),
('What adventure do you most want to go on with me?', 'Future & Dreams', 'Adventure', 180, 'medium', 1, 2, 'text', false),
('Describe your dream vacation destination for us', 'Future & Dreams', 'Travel', 240, 'medium', 1, 2, 'text', false),
('What skill do you want us to learn together?', 'Future & Dreams', 'Growth', 180, 'medium', 1, 2, 'text', false),
('How do you want our relationship to grow stronger?', 'Future & Dreams', 'Development', 240, 'medium', 3, 4, 'text', false),
('What does "growing old together" mean to you?', 'Future & Dreams', 'Aging', 240, 'medium', 3, 4, 'text', false),
('Describe our perfect retirement life', 'Future & Dreams', 'Retirement', 300, 'long', 2, 3, 'text', false),
('What challenge do you want us to overcome together?', 'Future & Dreams', 'Challenges', 240, 'medium', 3, 3, 'text', false),
('How do you want us to support each other''s individual dreams?', 'Future & Dreams', 'Support', 240, 'medium', 3, 3, 'text', false),
('What kind of couple do you want us to be known as?', 'Future & Dreams', 'Reputation', 180, 'medium', 2, 3, 'text', false),
('Describe the moment you want to say "we made it" together', 'Future & Dreams', 'Achievement', 240, 'medium', 2, 3, 'text', false),
('What yearly tradition do you want us to start?', 'Future & Dreams', 'Traditions', 180, 'medium', 1, 2, 'text', false),
('How do you want us to handle difficulties in the future?', 'Future & Dreams', 'Resilience', 300, 'long', 3, 4, 'text', false),
('What investment in our relationship would you prioritize?', 'Future & Dreams', 'Investment', 240, 'medium', 3, 3, 'text', false),

-- Memory & Nostalgia Text Cards (20 cards)
('Describe our first kiss in vivid detail', 'Memory & Nostalgia', 'Firsts', 240, 'medium', 1, 3, 'text', false),
('What was the funniest moment we''ve shared together?', 'Memory & Nostalgia', 'Humor', 180, 'medium', 1, 2, 'text', false),
('Write about a time I surprised you completely', 'Memory & Nostalgia', 'Surprises', 240, 'medium', 1, 2, 'text', false),
('Describe the most challenging time we''ve overcome together', 'Memory & Nostalgia', 'Challenges', 300, 'long', 3, 4, 'text', false),
('What is your favorite photo of us and why?', 'Memory & Nostalgia', 'Photos', 180, 'medium', 1, 2, 'text', false),
('Describe a moment when you felt most proud of us', 'Memory & Nostalgia', 'Pride', 240, 'medium', 2, 3, 'text', false),
('What was our best date ever and what made it special?', 'Memory & Nostalgia', 'Dates', 240, 'medium', 1, 2, 'text', false),
('Write about a time I made you laugh until you cried', 'Memory & Nostalgia', 'Laughter', 180, 'medium', 1, 2, 'text', false),
('Describe the moment you knew I was "the one"', 'Memory & Nostalgia', 'Realization', 240, 'medium', 3, 4, 'text', false),
('What is the most thoughtful thing I''ve ever done for you?', 'Memory & Nostalgia', 'Thoughtfulness', 240, 'medium', 1, 3, 'text', false),
('Write about our most passionate moment together', 'Memory & Nostalgia', 'Passion', 240, 'medium', 3, 5, 'text', false),
('Describe a time when I supported you through something difficult', 'Memory & Nostalgia', 'Support', 240, 'medium', 2, 3, 'text', false),
('What is your favorite conversation we''ve ever had?', 'Memory & Nostalgia', 'Communication', 240, 'medium', 2, 3, 'text', false),
('Write about a moment when you felt completely understood by me', 'Memory & Nostalgia', 'Understanding', 240, 'medium', 3, 4, 'text', false),
('Describe our most adventurous experience together', 'Memory & Nostalgia', 'Adventure', 240, 'medium', 1, 2, 'text', false),
('What is the silliest argument we''ve ever had?', 'Memory & Nostalgia', 'Arguments', 180, 'medium', 1, 2, 'text', false),
('Write about the first time we said "I love you"', 'Memory & Nostalgia', 'Love Declaration', 240, 'medium', 2, 4, 'text', false),
('Describe a moment when I exceeded your expectations', 'Memory & Nostalgia', 'Expectations', 240, 'medium', 2, 3, 'text', false),
('What holiday or celebration with me has been your favorite?', 'Memory & Nostalgia', 'Celebrations', 180, 'medium', 1, 2, 'text', false),
('Write about a time when we worked perfectly as a team', 'Memory & Nostalgia', 'Teamwork', 240, 'medium', 2, 3, 'text', false),

-- Intimate & Vulnerable Text Cards (20 cards)
('What is your biggest fear about our relationship?', 'Intimate & Vulnerable', 'Fears', 300, 'long', 4, 5, 'text', false),
('Describe something about yourself you''ve never told anyone', 'Intimate & Vulnerable', 'Secrets', 300, 'long', 4, 5, 'text', false),
('What do you need from me when you''re feeling most vulnerable?', 'Intimate & Vulnerable', 'Needs', 240, 'medium', 3, 4, 'text', false),
('Write about a time you felt completely safe with me', 'Intimate & Vulnerable', 'Safety', 240, 'medium', 3, 4, 'text', false),
('What is something you wish I knew about your past?', 'Intimate & Vulnerable', 'History', 300, 'long', 4, 4, 'text', false),
('Describe your deepest insecurity and how I can help', 'Intimate & Vulnerable', 'Insecurities', 300, 'long', 4, 5, 'text', false),
('What is one thing about intimacy that you want more of?', 'Intimate & Vulnerable', 'Intimacy Desires', 240, 'medium', 3, 5, 'text', false),
('Write about a time you felt misunderstood and how it affected you', 'Intimate & Vulnerable', 'Misunderstanding', 300, 'long', 4, 4, 'text', false),
('What is your greatest emotional need in our relationship?', 'Intimate & Vulnerable', 'Emotional Needs', 240, 'medium', 3, 4, 'text', false),
('Describe something that triggers you and why', 'Intimate & Vulnerable', 'Triggers', 300, 'long', 4, 5, 'text', false),
('What do you wish you could change about yourself for our relationship?', 'Intimate & Vulnerable', 'Self-Improvement', 300, 'long', 4, 4, 'text', false),
('Write about your most shameful moment and how you felt', 'Intimate & Vulnerable', 'Shame', 300, 'long', 5, 5, 'text', false),
('What is something you''re afraid to ask me for?', 'Intimate & Vulnerable', 'Unspoken Desires', 240, 'medium', 4, 4, 'text', false),
('Describe a time when you felt completely accepted by me', 'Intimate & Vulnerable', 'Acceptance', 240, 'medium', 3, 4, 'text', false),
('What is your biggest regret about our relationship so far?', 'Intimate & Vulnerable', 'Regrets', 300, 'long', 4, 5, 'text', false),
('Write about something you''ve been avoiding telling me', 'Intimate & Vulnerable', 'Avoidance', 300, 'long', 5, 5, 'text', false),
('What makes you feel most emotionally naked with me?', 'Intimate & Vulnerable', 'Emotional Nudity', 240, 'medium', 4, 5, 'text', false),
('Describe your deepest fantasy about our relationship', 'Intimate & Vulnerable', 'Fantasies', 300, 'long', 4, 5, 'text', false),
('What is one thing you need to forgive yourself for?', 'Intimate & Vulnerable', 'Self-Forgiveness', 300, 'long', 5, 4, 'text', false),
('Write about when you felt most emotionally connected to me', 'Intimate & Vulnerable', 'Emotional Connection', 240, 'medium', 3, 4, 'text', false);

-- Photo response cards (40 cards) - Visual challenges and creative tasks
INSERT INTO deck_cards (prompt, category, subcategory, timer_seconds, timer_category, difficulty_level, intimacy_level, response_type, requires_action) VALUES
-- Romantic & Sweet Photo Cards (15 cards)
('Take a selfie showing how you feel about me right now', 'Romantic & Sweet', 'Expression', 60, 'short', 1, 2, 'photo', false),
('Capture our hands intertwined in the most aesthetic way', 'Romantic & Sweet', 'Connection', 120, 'short', 1, 2, 'photo', false),
('Take a photo that represents our love story', 'Romantic & Sweet', 'Symbolism', 180, 'medium', 2, 3, 'photo', false),
('Show me your favorite photo of us on your phone', 'Romantic & Sweet', 'Memories', 60, 'short', 1, 2, 'photo', false),
('Create a heart shape with our shadows or reflections', 'Romantic & Sweet', 'Creativity', 180, 'medium', 2, 2, 'photo', false),
('Take a picture of something that reminds you of our first date', 'Romantic & Sweet', 'Nostalgia', 120, 'short', 1, 2, 'photo', false),
('Capture a romantic candlelit moment right now', 'Romantic & Sweet', 'Ambiance', 180, 'medium', 1, 3, 'photo', false),
('Take a photo of me looking at you with love', 'Romantic & Sweet', 'Gaze', 60, 'short', 1, 3, 'photo', false),
('Show me a sunset/sunrise view and dedicate it to our love', 'Romantic & Sweet', 'Nature', 120, 'short', 1, 2, 'photo', false),
('Create a flat lay of things that represent our relationship', 'Romantic & Sweet', 'Collection', 300, 'long', 2, 2, 'photo', false),
('Take a mirror selfie of us being cute together', 'Romantic & Sweet', 'Couple Goals', 90, 'short', 1, 2, 'photo', false),
('Capture me laughing at something you said', 'Romantic & Sweet', 'Joy', 60, 'short', 1, 2, 'photo', false),
('Take a photo of us recreating our first couple photo', 'Romantic & Sweet', 'Recreation', 180, 'medium', 1, 2, 'photo', false),
('Show me how you look when you''re thinking about me', 'Romantic & Sweet', 'Contemplation', 60, 'short', 1, 2, 'photo', false),
('Capture our reflection in something romantic', 'Romantic & Sweet', 'Reflection', 120, 'short', 2, 2, 'photo', false),

-- Flirty & Playful Photo Cards (10 cards)
('Take a seductive selfie that you''d send me if we were apart', 'Flirty & Playful', 'Seduction', 120, 'short', 2, 4, 'photo', false),
('Show me your best "come here" look', 'Flirty & Playful', 'Invitation', 60, 'short', 2, 3, 'photo', false),
('Take a photo highlighting your best physical feature', 'Flirty & Playful', 'Confidence', 120, 'short', 2, 3, 'photo', false),
('Capture yourself biting your lip in the sexiest way', 'Flirty & Playful', 'Tease', 60, 'short', 2, 3, 'photo', false),
('Take a playful photo of us being silly but sexy', 'Flirty & Playful', 'Playfulness', 90, 'short', 1, 3, 'photo', false),
('Show me what you''re wearing right now in an enticing way', 'Flirty & Playful', 'Fashion', 90, 'short', 2, 3, 'photo', false),
('Take a photo of your silhouette that''s artistic but alluring', 'Flirty & Playful', 'Artistry', 180, 'medium', 3, 4, 'photo', false),
('Capture yourself winking at the camera for me', 'Flirty & Playful', 'Wink', 30, 'short', 1, 2, 'photo', false),
('Take a photo showing off your smile that drives me crazy', 'Flirty & Playful', 'Smile', 60, 'short', 1, 3, 'photo', false),
('Show me your most photogenic angle with bedroom eyes', 'Flirty & Playful', 'Angles', 90, 'short', 2, 3, 'photo', false),

-- Creative & Fun Photo Cards (10 cards)
('Draw our future together and take a photo of your artwork', 'Creative & Fun', 'Art', 600, 'long', 2, 2, 'photo', false),
('Take a photo of something you''ve created that represents us', 'Creative & Fun', 'Creation', 300, 'long', 2, 2, 'photo', false),
('Capture yourself doing your silliest dance move', 'Creative & Fun', 'Dancing', 60, 'short', 1, 1, 'photo', false),
('Take a photo of food arranged to look like a heart', 'Creative & Fun', 'Food Art', 180, 'medium', 1, 1, 'photo', false),
('Show me your best impression of a movie character', 'Creative & Fun', 'Performance', 90, 'short', 2, 1, 'photo', false),
('Take a creative photo using only items from this room', 'Creative & Fun', 'Resourcefulness', 300, 'long', 2, 1, 'photo', false),
('Capture yourself wearing something of mine', 'Creative & Fun', 'Fashion', 90, 'short', 1, 2, 'photo', false),
('Take a photo that tells our love story in one image', 'Creative & Fun', 'Storytelling', 240, 'medium', 3, 3, 'photo', false),
('Show me your funniest facial expression', 'Creative & Fun', 'Humor', 30, 'short', 1, 1, 'photo', false),
('Create and photograph a message using objects around you', 'Creative & Fun', 'Communication', 300, 'long', 2, 2, 'photo', false),

-- Daily Life Photo Cards (5 cards)
('Take a photo of your current view and tell me why it''s special', 'Daily Life', 'Perspective', 60, 'short', 1, 1, 'photo', false),
('Show me what you''re snacking on right now', 'Daily Life', 'Food', 30, 'short', 1, 1, 'photo', false),
('Take a photo of your workspace/environment today', 'Daily Life', 'Environment', 60, 'short', 1, 1, 'photo', false),
('Capture something that made you think of me today', 'Daily Life', 'Reminders', 90, 'short', 1, 2, 'photo', false),
('Take a photo of yourself in your most comfortable clothes', 'Daily Life', 'Comfort', 60, 'short', 1, 2, 'photo', false);