-- Insert mock events for testing the UI
INSERT INTO public.events (
  title, 
  description, 
  event_date, 
  event_time, 
  location_name, 
  location_address, 
  latitude, 
  longitude, 
  category, 
  price_range, 
  organizer, 
  source_url, 
  source_platform, 
  image_url, 
  tags
) VALUES 
(
  'Wine Tasting Evening', 
  'Romantic wine tasting with live jazz music and artisanal cheese pairings', 
  '2025-08-07', 
  '19:00', 
  'Vineyard Lounge', 
  '123 Wine Street, San Francisco, CA', 
  37.7749, 
  -122.4194, 
  'romantic', 
  '$50-$80', 
  'Vineyard Events', 
  'https://example.com/wine-tasting', 
  'mock', 
  null, 
  ARRAY['wine', 'romantic', 'music']
),
(
  'Sunset Beach Walk', 
  'Scenic coastal walk with breathtaking sunset views and photography opportunities', 
  '2025-08-08', 
  '18:30', 
  'Ocean Beach', 
  'Ocean Beach, San Francisco, CA', 
  37.7594, 
  -122.5107, 
  'romantic', 
  'Free', 
  'City Parks Department', 
  'https://example.com/beach-walk', 
  'mock', 
  null, 
  ARRAY['outdoor', 'sunset', 'free', 'photography']
),
(
  'Cooking Class for Couples', 
  'Learn to cook authentic Italian cuisine together with professional chef guidance', 
  '2025-08-09', 
  '15:00', 
  'Culinary Arts Center', 
  '456 Food Avenue, San Francisco, CA', 
  37.7849, 
  -122.4094, 
  'food', 
  '$120-$150', 
  'Culinary Academy', 
  'https://example.com/cooking-class', 
  'mock', 
  null, 
  ARRAY['cooking', 'couples', 'italian', 'education']
),
(
  'Jazz Night at Blue Note', 
  'Intimate jazz performance featuring local artists in a cozy atmosphere', 
  '2025-08-10', 
  '20:00', 
  'Blue Note Jazz Club', 
  '789 Music Lane, San Francisco, CA', 
  37.7849, 
  -122.4194, 
  'music', 
  '$25-$40', 
  'Blue Note Venues', 
  'https://example.com/jazz-night', 
  'mock', 
  null, 
  ARRAY['jazz', 'music', 'nightlife', 'intimate']
),
(
  'Art Gallery Opening', 
  'Contemporary art exhibition opening with wine reception', 
  '2025-08-11', 
  '17:00', 
  'Modern Art Gallery', 
  '321 Art District, San Francisco, CA', 
  37.7649, 
  -122.4094, 
  'cultural', 
  '$15-$25', 
  'Modern Art Collective', 
  'https://example.com/art-opening', 
  'mock', 
  null, 
  ARRAY['art', 'gallery', 'wine', 'cultural']
);