// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkcszcrestnnowiapagi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrY3N6Y3Jlc3Rubm93aWFwYWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzUyOTUsImV4cCI6MjA2ODYxMTI5NX0.uek4GmIy1aQF4ZWb5V0-dBoBVAzUMn7yOi7TJDs-MlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});